# Generated by Django 3.1.2 on 2020-10-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user', verbose_name='user')),
                ('image', models.ImageField(blank=True, upload_to='uploads/profile_images/%Y/%m/%d/', verbose_name='image')),
                ('state', models.CharField(choices=[('JHR', 'JHR'), ('KDH', 'KDH'), ('KTN', 'KTN'), ('MLK', 'MLK'), ('NSN', 'NSN'), ('PHG', 'PHG'), ('PNG', 'PNG'), ('PRK', 'PRK'), ('PLS', 'PLS'), ('SBH', 'SBH'), ('SWK', 'SWK'), ('SGR', 'SGR'), ('TRG', 'TRG'), ('KUL', 'KUL'), ('LBN', 'LBN'), ('PJY', 'PJY')], max_length=3, verbose_name='state')),
            ],
        ),
    ]
