# Generated by Django 3.1.2 on 2020-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarry',
            name='grid_reference',
        ),
        migrations.AddField(
            model_name='quarry',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarry',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
