# Generated by Django 3.1.2 on 2020-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarry',
            old_name='pengusaha_kuari',
            new_name='quarry_entrepreneur',
        ),
        migrations.AlterField(
            model_name='quarry',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (line 2)'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (line 3)'),
        ),
    ]
