# Generated by Django 3.1.2 on 2020-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarry',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
