# Generated by Django 3.1.2 on 2020-10-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0002_auto_20201005_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarry',
            old_name='leaseholders',
            new_name='leaseholder',
        ),
    ]
