# Generated by Django 3.1.2 on 2020-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0003_auto_20201005_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessubmission',
            name='inch_5_8_amount',
            field=models.DecimalField(decimal_places=4, default=21, max_digits=15, verbose_name='amaun 5/8"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salessubmission',
            name='inch_5_8_worth',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=15, verbose_name='nilai 5/8"'),
            preserve_default=False,
        ),
    ]
