# Generated by Django 3.1.2 on 2020-11-16 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0004_auto_20201116_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseholder',
            name='lease_expired',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='tarikh tamat pajakan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Keluasan (Hektar)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='lease_number',
            field=models.CharField(max_length=255, verbose_name='No Pajakan / No Hakmilik / No Lot'),
        ),
    ]
