# Generated by Django 3.1.2 on 2020-10-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0004_auto_20201006_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportFinalUse',
            new_name='ExportFinalUses',
        ),
        migrations.RenameModel(
            old_name='LocalFinalUse',
            new_name='LocalFinalUses',
        ),
    ]
