# Generated by Django 3.1.2 on 2020-10-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0005_auto_20201006_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfinaluses',
            name='calcium_carbonate_powder_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai serbuk kalsium karbonat'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='cement_making_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai pembuatan simen'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='construction_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai pembinaan'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='dimension_stone_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai batu dimensi'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='dolomite_powder_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai serbuk dolomit'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='fertilizer_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai baja'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='hydrated_lime_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai kapur hidrat'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='other_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai lain'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='premix_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai premix'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='quicklime_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai kapur tohor'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='ready_mix_concrete_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai konkrit readymix'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='steel_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai industri keluli'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='terrazo_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai terazo'),
        ),
    ]
