# Generated by Django 3.1.2 on 2020-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0006_auto_20201116_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseholder',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
        migrations.AlterField(
            model_name='salessubmission',
            name='submission_size',
            field=models.CharField(max_length=255, verbose_name='Saiz Batuan/Produk'),
        ),
        migrations.AlterField(
            model_name='salessubmission',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Jumlah (RM)'),
        ),
    ]
