# Generated by Django 3.1.2 on 2020-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0006_auto_20201006_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricmachinery',
            name='total_number',
            field=models.IntegerField(default=0, verbose_name='jumlah bilangan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricmachinery',
            name='total_power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='jumlah_kuasa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcombustionmachinery',
            name='total_number',
            field=models.IntegerField(default=0, verbose_name='jumlah bilangan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcombustionmachinery',
            name='total_power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='jumlah_kuasa'),
            preserve_default=False,
        ),
    ]
