# Generated by Django 3.1.2 on 2020-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0007_auto_20201121_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmission',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (RM)'),
        ),
    ]
