# Generated by Django 3.1.2 on 2020-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0008_auto_20201006_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='comment',
            field=models.TextField(blank=True, verbose_name='komen'),
        ),
        migrations.AlterField(
            model_name='other',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='tajuk'),
        ),
    ]
