# Generated by Django 3.1.2 on 2020-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0008_auto_20201122_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfinaluses',
            name='other_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='amaun lain'),
        ),
        migrations.AlterField(
            model_name='exportfinaluses',
            name='other_worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='nilai lain'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='other_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='amaun lain'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='other_worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='nilai lain'),
        ),
        migrations.AlterField(
            model_name='salessubmission',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Jumlah (RM)'),
        ),
    ]
