# Generated by Django 3.1.2 on 2020-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarry', '0009_auto_20201122_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfinaluses',
            name='other_amount',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='amaun lain'),
        ),
        migrations.AlterField(
            model_name='exportfinaluses',
            name='other_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai lain'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='other_amount',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='amaun lain'),
        ),
        migrations.AlterField(
            model_name='localfinaluses',
            name='other_worth',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='nilai lain'),
        ),
    ]
