# Generated by Django 3.1.2 on 2020-10-09 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarry', '0009_auto_20201007_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarryApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_comment', models.TextField(blank=True, verbose_name='state comment')),
                ('state_approved', models.BooleanField(blank=True, null=True, verbose_name='state approved')),
                ('admin_comment', models.TextField(blank=True, verbose_name='admin comment')),
                ('admin_approved', models.BooleanField(blank=True, null=True, verbose_name='admin approved')),
                ('hq_comment', models.TextField(blank=True, verbose_name='hq comment')),
                ('hq_approved', models.BooleanField(blank=True, null=True, verbose_name='hq approved')),
                ('admin_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quary_admin_inspected', to=settings.AUTH_USER_MODEL, verbose_name='admin inspector')),
                ('hq_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quary_hq_inspected', to=settings.AUTH_USER_MODEL, verbose_name='hq inspector')),
                ('quarry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarry.quarry', verbose_name='quarry')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quary_requested', to=settings.AUTH_USER_MODEL, verbose_name='requestor')),
                ('state_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quary_state_inspected', to=settings.AUTH_USER_MODEL, verbose_name='state inspector')),
            ],
        ),
    ]
