# Generated by Django 3.1.2 on 2020-10-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarry', '0010_quarryapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarry',
            name='company_category',
            field=models.CharField(max_length=255, verbose_name='kategori syarikat'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='main_rock_type',
            field=models.CharField(max_length=255, verbose_name='jenis batuan utama'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='side_rock_type',
            field=models.CharField(max_length=255, verbose_name='jenis batuan sampingan'),
        ),
        migrations.AlterField(
            model_name='quarryapproval',
            name='admin_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarry_admin_inspected', to=settings.AUTH_USER_MODEL, verbose_name='admin inspector'),
        ),
        migrations.AlterField(
            model_name='quarryapproval',
            name='hq_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarry_hq_inspected', to=settings.AUTH_USER_MODEL, verbose_name='hq inspector'),
        ),
        migrations.AlterField(
            model_name='quarryapproval',
            name='quarry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='quarry.quarry', verbose_name='quarry'),
        ),
        migrations.AlterField(
            model_name='quarryapproval',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarry_requested', to=settings.AUTH_USER_MODEL, verbose_name='requestor'),
        ),
        migrations.AlterField(
            model_name='quarryapproval',
            name='state_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarry_state_inspected', to=settings.AUTH_USER_MODEL, verbose_name='state inspector'),
        ),
    ]
