# Generated by Django 3.1.2 on 2020-10-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quarry.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0002_auto_20201101_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_comment', models.TextField(blank=True, verbose_name='state comment')),
                ('state_approved', models.BooleanField(blank=True, null=True, verbose_name='state approved')),
                ('admin_comment', models.TextField(blank=True, verbose_name='admin comment')),
                ('admin_approved', models.BooleanField(blank=True, null=True, verbose_name='admin approved')),
                ('hq_comment', models.TextField(blank=True, verbose_name='hq comment')),
                ('hq_approved', models.BooleanField(blank=True, null=True, verbose_name='hq approved')),
                ('admin_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_admin_inspected', to=settings.AUTH_USER_MODEL, verbose_name='admin inspector')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('JHR', 'Johor'), ('KDH', 'Kedah'), ('KTN', 'Kelantan'), ('MLK', 'Melaka'), ('NSN', 'Negeri Sembilan'), ('PHG', 'Pahang'), ('PNG', 'Pulau Pinang'), ('PRK', 'Perak'), ('PLS', 'Perlis'), ('SBH', 'Sabah'), ('SWK', 'Sarawak'), ('SGR', 'Selangor'), ('TRG', 'Terengganu'), ('KUL', 'Kuala Lumpur'), ('LBN', 'Labuan'), ('PJY', 'Putrajaya')], max_length=3, verbose_name='negeri')),
                ('month', models.PositiveIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Mac'), (4, 'April'), (5, 'Mei'), (6, 'Jun'), (7, 'Julai'), (8, 'Ogos'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Disember')], verbose_name='bulan')),
                ('year', models.PositiveIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=quarry.models.current_year, verbose_name='tahun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_data', to='mine.manager', verbose_name='pengusaha')),
                ('mine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='mine.mine', verbose_name='lombong')),
            ],
            options={
                'verbose_name': 'data kuari',
                'verbose_name_plural': 'data kuari',
            },
        ),
        migrations.RemoveField(
            model_name='mineminer',
            name='add_by',
        ),
        migrations.RemoveField(
            model_name='mineminer',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='mineminer',
            name='miner',
        ),
        migrations.RemoveField(
            model_name='mineminerdata',
            name='mine',
        ),
        migrations.RemoveField(
            model_name='mineminerdata',
            name='miner',
        ),
        migrations.RemoveField(
            model_name='electricmachinery',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='energysupply',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='foreigncontractor',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='foreignoperator',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='internalcombustionmachinery',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='localcontractor',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='localoperator',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='mainstatistic',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='operatingrecord',
            name='miner_data',
        ),
        migrations.RemoveField(
            model_name='sidestatistic',
            name='miner_data',
        ),
        migrations.DeleteModel(
            name='MineDataApproval',
        ),
        migrations.DeleteModel(
            name='MineMiner',
        ),
        migrations.DeleteModel(
            name='MineMinerData',
        ),
        migrations.AddField(
            model_name='approval',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mine.data', verbose_name='miner data'),
        ),
        migrations.AddField(
            model_name='approval',
            name='hq_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_hq_inspected', to=settings.AUTH_USER_MODEL, verbose_name='hq inspector'),
        ),
        migrations.AddField(
            model_name='approval',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_requested', to=settings.AUTH_USER_MODEL, verbose_name='requestor'),
        ),
        migrations.AddField(
            model_name='approval',
            name='state_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_state_inspected', to=settings.AUTH_USER_MODEL, verbose_name='state inspector'),
        ),
        migrations.AddField(
            model_name='electricmachinery',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energysupply',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreigncontractor',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreignoperator',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcombustionmachinery',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localcontractor',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localoperator',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainstatistic',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_minerals', to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingrecord',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidestatistic',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='side_minerals', to='mine.data', verbose_name='miner data'),
            preserve_default=False,
        ),
    ]
