# Generated by Django 3.1.2 on 2020-10-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0002_auto_20201007_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_comment', models.TextField(blank=True, verbose_name='state comment')),
                ('state_approved', models.BooleanField(blank=True, null=True, verbose_name='state approved')),
                ('admin_comment', models.TextField(blank=True, verbose_name='admin comment')),
                ('admin_approved', models.BooleanField(blank=True, null=True, verbose_name='admin approved')),
                ('hq_comment', models.TextField(blank=True, verbose_name='hq comment')),
                ('hq_approved', models.BooleanField(blank=True, null=True, verbose_name='hq approved')),
                ('admin_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_admin_inspected', to=settings.AUTH_USER_MODEL, verbose_name='admin inspector')),
                ('hq_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_hq_inspected', to=settings.AUTH_USER_MODEL, verbose_name='hq inspector')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mine.mine', verbose_name='mine')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_requested', to=settings.AUTH_USER_MODEL, verbose_name='requestor')),
                ('state_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mine_state_inspected', to=settings.AUTH_USER_MODEL, verbose_name='state inspector')),
            ],
        ),
    ]
