# Generated by Django 3.1.2 on 2020-10-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0003_mainmineral_sidemineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mine.manager', verbose_name='pengurus'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='lease_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.leaseholder', verbose_name='pemajak'),
        ),
    ]
