# Generated by Django 3.1.2 on 2020-10-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_auto_20201030_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='lease_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mines_managered', serialize=False, to='mine.leaseholder', verbose_name='pemajak'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mine.manager', verbose_name='pengurus'),
        ),
    ]
