# Generated by Django 3.1.2 on 2020-11-04 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine', '0004_auto_20201103_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='MineManager',
        ),
        migrations.AlterModelOptions(
            name='mainmineral',
            options={'verbose_name': 'mineral utama', 'verbose_name_plural': 'mineral utama'},
        ),
        migrations.AlterModelOptions(
            name='sidemineral',
            options={'verbose_name': 'mineral sampingan', 'verbose_name_plural': 'mineral sampingan'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='electricmachinery',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='energysupply',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='foreigncontractor',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='foreignoperator',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='internalcombustionmachinery',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='localcontractor',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='localoperator',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='mainstatistic',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_minerals', to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mine.data', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='sidestatistic',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_minerals', to='mine.data', verbose_name='data'),
        ),
    ]
