# Generated by Django 3.1.2 on 2020-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0005_auto_20201105_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstatistic',
            name='minerals_quantity',
        ),
        migrations.RemoveField(
            model_name='sidestatistic',
            name='minerals_quantity',
        ),
        migrations.AddField(
            model_name='mainstatistic',
            name='quantity_unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('M3', 'Meter Persegi'), ('GRAM', 'Gram'), ('TAN', 'Tan')], default='TAN', max_length=255, verbose_name='unit kuantiti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidestatistic',
            name='quantity_unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('M3', 'Meter Persegi'), ('GRAM', 'Gram'), ('TAN', 'Tan')], default='TAN', max_length=255, verbose_name='unit kuantiti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainstatistic',
            name='mineral_type',
            field=models.CharField(max_length=255, verbose_name='jenis mineral utama'),
        ),
    ]
