# Generated by Django 3.1.2 on 2020-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_auto_20201028_1306'),
        ('mine', '0005_auto_20201029_0131'),
    ]

    operations = [
    ]
