# Generated by Django 3.1.2 on 2020-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0006_auto_20201106_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstatistic',
            name='mineral_type',
            field=models.CharField(choices=[('BAUXITE', 'Bauksite/Bauksit'), ('TIN ORE', 'Tin Ore/Bijih Timah'), ('IRON ORE', 'Iron Ore/Bijih Besi'), ('ANTIMONY', 'Antimony/Antimoni'), ('COAL', 'Coal/Arang Batu'), ('DIMENSION STONE', 'Dimension Stone/Batu Dimensi'), ('FELDSPAR', 'Feldspar/Felspar'), ('GALENA', 'Galena/Galena'), ('BATU KAPUR', 'Limestone/Batu Kapur'), ('KAOLIN', 'Kaolin'), ('CUPRUM', 'Kuprum'), ('BALL CLAY', 'Ball Clay/Lempung Bebola'), ('MANGANESE', 'Manganese/Mangan'), ('MICA', 'Mica/Mika'), ('SILVER', 'Silver/Perak'), ('SILICA SAND', 'Silica Sand/Pasir Silika'), ('TUNGSTEN', 'Tungsten'), ('GOLD', 'Gold/Emas'), ('GRAPHITE', 'Graphite/Grafit')], max_length=255, verbose_name='jenis mineral utama'),
        ),
        migrations.AlterField(
            model_name='mainstatistic',
            name='quantity_unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('M3', 'Meter Persegi'), ('GRAM', 'Gram'), ('TAN', 'Tan')], default='TAN', max_length=255, verbose_name='unit kuantiti'),
        ),
        migrations.AlterField(
            model_name='sidestatistic',
            name='quantity_unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('M3', 'Meter Persegi'), ('GRAM', 'Gram'), ('TAN', 'Tan')], default='TAN', max_length=255, verbose_name='unit kuantiti'),
        ),
    ]
