# Generated by Django 3.1.2 on 2020-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0007_auto_20201109_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseholder',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='keluasan (Hektar)'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='lease_expired',
            field=models.DateField(blank=True, verbose_name='tarikh tamat pajakan'),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='lease_number',
            field=models.CharField(max_length=255, verbose_name='no pajakan'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='alamat (No Rumah, Nama Jalan)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Daerah)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (Poskod, Negeri)'),
        ),
    ]
