# Generated by Django 3.1.2 on 2021-01-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstatistic',
            options={'verbose_name': 'perangkaan lesen proses', 'verbose_name_plural': 'perangkaan lesen proses'},
        ),
    ]
