# Generated by Django 3.1.2 on 2021-02-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0003_auto_20210127_1219'),
        ('mineral', '0002_auto_20210204_1359'),
    ]

    operations = [
    ]
