# Generated by Django 3.1.2 on 2020-10-10 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='nama syarikat')),
                ('company_address', models.CharField(max_length=255, verbose_name='alamat syarikat')),
                ('company_state', models.CharField(max_length=50, verbose_name='negeri')),
                ('company_phone', models.CharField(max_length=50, verbose_name='no phone')),
                ('company_fax', models.CharField(max_length=50, verbose_name='no fax')),
                ('company_email', models.CharField(max_length=255, verbose_name='emel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'syarikat',
                'verbose_name_plural': 'syarikat',
            },
        ),
    ]
