# Generated by Django 3.1.2 on 2020-10-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='address1',
            field=models.CharField(default='awsdfasd', max_length=255, verbose_name='alamat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (line 2)'),
        ),
        migrations.AddField(
            model_name='company',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='alamat (line 3)'),
        ),
    ]
